Cómo vamos a manejar errores con Fetch API?

Vamos a ver cómo podemos lidiar con errores tanto de la forma tradicional,
(.then()), cómo con async/await


* En el caso de Fetch API (método tradicional):


const fetchPost = () => {
fetch('https://jsonplaceholder.typicode.com/posts?_limit=10')
   .then((response) => {
      if (!response.ok) {
         throw Error(response.statusText);
      }
      return response.json();
   })
   .then((data) => {
      console.log(data);
      setPosts(data);
   })
   .catch((err) => {
      console.log(err.message);
   });
};



* En el caso de async/await vamos a contar con try y catch para manjear errores:


const fetchPost = async () => {
   try {
      const response = await fetch(
         'https://jsonplaceholder.typicode.com/posts?_limit=10'
      );
      const data = await response.json();
      setPosts(data);
   } catch (error) {
      console.log(error);
   }
};
